version: '3'
services:
  {{ project_name }}:
    container_name: {{ project_name }}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - {{ port }}:8000
    command: [ "gunicorn", "-c", "/{{ project_name }}/gunicorn_config.py", "app:app" ]
