version: '3'
services:
  {{ project_name }}:
    container_name: {{ project_name }}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/project
    ports:
      - {{ port }}:8000
    command: [ "gunicorn", "-c", "/project/gunicorn_config.py", "project.app:app" ]
