version: '3'
services:
  {{project-name}}:
    container_name: {{project-name}}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: [ "gunicorn", "-c", "/{{project-name}}/gunicorn_config.py", "app:app" ]